version: "3.8"
services:
  redis-test:
    image: redis:7-alpine
    container_name: amocrm_redis_test_instance
    ports:
      - "6380:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./redis_data:/data